In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
x=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

In [3]:
maxabs=preprocessing.MaxAbsScaler()
x_scaled=maxabs.fit_transform(x)
print(x_scaled)

[[-0.55555556]
 [-0.11111111]
 [ 0.        ]
 [ 0.11111111]
 [ 1.        ]]


In [4]:
x1=np.array([[1,2,3],[-4,5,-6],[7,-8,9]])

In [5]:
x_scaled1=maxabs.fit_transform(x1)
print(x_scaled1)

[[ 0.14285714  0.25        0.33333333]
 [-0.57142857  0.625      -0.66666667]
 [ 1.         -1.          1.        ]]


In [7]:
import pandas as pd

In [9]:
df=pd.DataFrame(np.random.randn(4,5),columns=np.arange(5))
print(df)

          0         1         2         3         4
0 -0.376364  0.202652  0.435225 -0.117076 -1.242801
1  1.381476 -1.597553  0.125535  2.052219 -0.266235
2  1.430332 -1.227324  0.643463  0.409984 -0.648673
3  0.454877  0.458113 -0.423107 -1.614137 -1.364378


In [10]:
x_scaled2=maxabs.fit_transform(df)
print(x_scaled2)

[[-0.2631304   0.12685128  0.67637862 -0.0570484  -0.91089198]
 [ 0.96584342 -1.          0.19509272  1.         -0.19513306]
 [ 1.         -0.76825218  1.          0.19977622 -0.47543469]
 [ 0.31802241  0.2867588  -0.65754662 -0.78653272 -1.        ]]
