In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
x=np.array([[1,2],[2,5],[3,6],[4,9],[5,8]])

In [3]:
normalizer=preprocessing.Normalizer()
normal=normalizer.fit_transform(x)
print(normal)

[[0.4472136  0.89442719]
 [0.37139068 0.92847669]
 [0.4472136  0.89442719]
 [0.40613847 0.91381155]
 [0.52999894 0.8479983 ]]


In [4]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
normalizer1=preprocessing.Normalizer()
normal1=normalizer1.fit_transform(x)
print(normal1)

[[0.4472136  0.89442719]
 [0.37139068 0.92847669]
 [0.4472136  0.89442719]
 [0.40613847 0.91381155]
 [0.52999894 0.8479983 ]]


### **Performing on Pandas Dataset**

In [6]:
import pandas as pd

In [7]:
from google.colab import files
uploaded=files.upload()

Saving new_train.csv to new_train.csv


In [9]:
dataset=pd.read_csv('new_train.csv',header=None)

In [10]:
dataset.head()

0          1
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [11]:
features=dataset.iloc[0:4,:].values

In [13]:
normalizer2=preprocessing.Normalizer()
normal2=normalizer2.fit_transform(features)
print(normal2)

[[0.74407288 0.66809845]
 [0.72525678 0.68847847]
 [0.65685808 0.75401423]
 [0.72037889 0.69358075]]
