In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
x=np.array([[-400],
            [-100],
            [0],
            [100],
            [400]])

In [4]:
standardscaler=preprocessing.StandardScaler()
x_scaler=standardscaler.fit_transform(x)
print(x_scaler)

[[-1.53392998]
 [-0.38348249]
 [ 0.        ]
 [ 0.38348249]
 [ 1.53392998]]


### **Applying it to 3*3 Matrix**

In [5]:
x1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [6]:
standardscaler1=preprocessing.StandardScaler()
x_scaler1=standardscaler1.fit_transform(x1)
print(x_scaler1)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


### **Applying this on Pandas Dataset**

In [7]:
import pandas as pd

In [8]:
from google.colab import files
uploaded=files.upload()

Saving Weather.csv to Weather.csv


In [9]:
dataset=pd.read_csv('Weather.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7,8,18,25) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [10]:
dataset.head()

STA      Date Precip  WindGustSpd    MaxTemp  ...  SD3  RHX RHN RVG  WTE
0  10001  1942-7-1  1.016          NaN  25.555556  ...  NaN  NaN NaN NaN  NaN
1  10001  1942-7-2      0          NaN  28.888889  ...  NaN  NaN NaN NaN  NaN
2  10001  1942-7-3   2.54          NaN  26.111111  ...  NaN  NaN NaN NaN  NaN
3  10001  1942-7-4   2.54          NaN  26.666667  ...  NaN  NaN NaN NaN  NaN
4  10001  1942-7-5      0          NaN  26.666667  ...  NaN  NaN NaN NaN  NaN

[5 rows x 31 columns]

In [11]:
features=dataset.iloc[0:4,4:7].values

In [14]:
features

array([[25.55555556, 22.22222222, 23.88888889],
       [28.88888889, 21.66666667, 25.55555556],
       [26.11111111, 22.22222222, 24.44444444],
       [26.66666667, 22.22222222, 24.44444444]])

In [16]:
standardscaler2=preprocessing.StandardScaler()
x_scaler2=standardscaler2.fit_transform(features)

In [20]:
print(x_scaler2)

[[-0.98787834  0.57735027 -1.14707866]
 [ 1.6464639  -1.73205081  1.60591014]
 [-0.5488213   0.57735027 -0.22941574]
 [-0.10976426  0.57735027 -0.22941574]]
